DEALER_PEDS_CASINO = {
    {
        model = "S_M_Y_Casino_01",
        idleAnim = 'idle',
        componentVariations = {
            {
                {comp = 0, drwb = 3, txt = 0, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 3, txt = 0, p = 0},
                {comp = 3, drwb = 1, txt = 0, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 3, txt = 0, p = 0},
                {comp = 10, drwb = 1, txt = 0, p = 0},
                {comp = 11, drwb = 1, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 2, txt = 2, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 4, txt = 0, p = 0},
                {comp = 3, drwb = 0, txt = 3, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 1, txt = 0, p = 0},
                {comp = 10,drwb = 1, txt = 0, p = 0},
                {comp = 11,drwb = 1, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 2, txt = 1, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 2, txt = 0, p = 0},
                {comp = 3, drwb = 0, txt = 3, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 1, txt = 0, p = 0},
                {comp = 10,drwb = 1,txt = 0, p = 0},
                {comp = 11,drwb = 1,txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 2, txt= 0, p = 0},
                {comp = 1, drwb = 1, txt= 0, p = 0},
                {comp = 2, drwb = 3, txt= 0, p = 0},
                {comp = 3, drwb = 1, txt= 3, p = 0},
                {comp = 4, drwb = 0, txt= 0, p = 0},
                {comp = 6, drwb = 1, txt= 0, p = 0},
                {comp = 7, drwb = 2, txt= 0, p = 0},
                {comp = 8, drwb = 3, txt= 0, p = 0},
                {comp = 10, drwb = 1, txt= 0, p = 0},
                {comp = 11, drwb = 1, txt= 0, p = 0},
            },
            {
                {comp = 0, drwb = 4, txt = 2, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 3, txt = 0, p = 0},
                {comp = 3, drwb = 0, txt = 0, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 1, txt = 0, p = 0},
                {comp = 10, drwb = 1, txt = 0, p = 0},
                {comp = 11, drwb = 1, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 4, txt = 0, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 0, txt = 0, p = 0},
                {comp = 3, drwb = 0, txt = 0, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 1, txt = 0, p = 0},
                {comp = 10, drwb = 1, txt = 0, p = 0},
                {comp = 11, drwb = 1, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 4, txt = 1, p = 0},
                {comp = 1, drwb = 1, txt = 0, p = 0},
                {comp = 2, drwb = 4, txt = 0, p = 0},
                {comp = 3, drwb = 1, txt = 0, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 1, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 3, txt = 0, p = 0},
                {comp = 10, drwb = 1, txt = 0, p = 0},
                {comp = 11, drwb = 1, txt = 0, p = 0},
            }
        },
    },
    {
        model = 'S_F_Y_Casino_01',
        idleAnim = 'female_idle',
        componentVariations = {
            {
                {comp = 0, drwb = 1, txt = 1, p = 0},
                {comp = 1, drwb = 0, txt = 0, p = 0},
                {comp = 2, drwb = 1, txt = 0, p = 0},
                {comp = 3, drwb = 0, txt = 3, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 0, txt = 0, p = 0},
                {comp = 7, drwb = 0, txt = 0, p = 0},
                {comp = 8, drwb = 0, txt = 0, p = 0},
                {comp = 10, drwb = 0, txt = 0, p = 0},
                {comp = 11, drwb = 0, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 1, txt = 1, p = 0},
                {comp = 1, drwb = 0, txt = 0, p = 0},
                {comp = 2, drwb = 1, txt = 1, p = 0},
                {comp = 3, drwb = 1, txt = 3, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 0, txt = 0, p = 0},
                {comp = 7, drwb = 2, txt = 0, p = 0},
                {comp = 8, drwb = 1, txt = 0, p = 0},
                {comp = 10, drwb = 0, txt = 0, p = 0},
                {comp = 11, drwb = 0, txt = 0, p = 0},
            },
            {
                {comp = 0, drwb = 2, txt = 0, p = 0},
                {comp = 1, drwb = 0, txt = 0, p = 0},
                {comp = 2, drwb = 2, txt = 0, p = 0},
                {comp = 3, drwb = 2, txt = 3, p = 0},
                {comp = 4, drwb = 0, txt = 0, p = 0},
                {comp = 6, drwb = 0, txt = 0, p = 0},
                {comp = 7, drwb = 0, txt = 0, p = 0},
                {comp = 8, drwb = 2, txt = 0, p = 0},
                {comp = 10, drwb = 0, txt = 0, p = 0},
                {comp = 11, drwb = 0, txt = 0, p = 0},
            }
        }
    }

}