---------------------------------------------------------------------------------------
---------------------------------- GTA MODIFICATIONS ----------------------------------
---------------------------------------------------------------------------------------
-- All the base GTA modifications. You *probably* won't need to modify this file
-- unless you a nerd and know what you are going. In that case, have fun <3
---------------------------------------------------------------------------------------

Config.Mods = {}

Config.Mods.ItemsRequired = {
  repair = { itemName = "repair_kit", removeItem = true },
  performance = { itemName = "performance_part", removeItem = true },
  cosmetics = { itemName = "cosmetic_part", removeItem = true },
  stance = { itemName = "stancing_kit", removeItem = false },
  respray = { itemName = "respray_kit", removeItem = true },
  wheels = { itemName = "vehicle_wheels", removeItem = true },
  neonLights = { itemName = "lighting_controller", removeItem = true },
  headlights = { itemName = "lighting_controller", removeItem = true },
  tyreSmoke = { itemName = "tyre_smoke_kit", removeItem = true },
  bulletproofTyres = { itemName = "bulletproof_tyres", removeItem = true },
  extras = { itemName = "extras_kit", removeItem = true }
}

Config.Mods.Performance = {
  { modType = 11, name = "Engine", overrideOptions = {
    { modIndex = 0, name = "EMS Upgrade, Level 1" },
    { modIndex = 1, name = "EMS Upgrade, Level 2" },
    { modIndex = 2, name = "EMS Upgrade, Level 3" },
    { modIndex = 3, name = "EMS Upgrade, Level 4" }
  } },
  { modType = 12, name = "Brakes", overrideOptions = {
    { modIndex = 0, name = "Street Brakes" },
    { modIndex = 1, name = "Sport Brakes" },
    { modIndex = 2, name = "Race Brakes" }
  } },
  { modType = 13, name = "Transmission", overrideOptions = {
    { modIndex = 0, name = "Street Transmission" },
    { modIndex = 1, name = "Sports Transmission" },
    { modIndex = 2, name = "Race Transmission" }
  } },
  { modType = 15, name = "Suspension", overrideOptions = {
    { modIndex = 0, name = "Lowered Suspension" },
    { modIndex = 1, name = "Street Suspension" },
    { modIndex = 2, name = "Sport Suspension" },
    { modIndex = 3, name = "Competition Suspension" }
  } },
  { modType = 16, name = "Armour", overrideOptions = {
    { modIndex = 0, name = "Armor Upgrade 20%" },
    { modIndex = 1, name = "Armor Upgrade 40%" },
    { modIndex = 2, name = "Armor Upgrade 60%" },
    { modIndex = 3, name = "Armor Upgrade 80%" },
    { modIndex = 4, name = "Armor Upgrade 100%" }
  } },
  { modType = 18, name = "Turbocharging", toggle = true } 
}

Config.Mods.Cosmetics = {
  { modType = 0, name = "扰流板" },
  { modType = 1, name = "前保险杠" },
  { modType = 2, name = "后保险杠" },
  { modType = 3, name = "侧裙" },
  { modType = 4, name = "排气管" },
  { modType = 5, name = "底盘" },
  { modType = 6, name = "格栅" },
  { modType = 7, name = "引擎盖" },
  { modType = 8, name = "左翼" },
  { modType = 9, name = "右翼" },
  { modType = 10, name = "车顶" },
  { modType = 14, name = "喇叭", ignorePriceMult = true },
  { modType = 19, name = "低音炮" },
  { modType = 21, name = "液压系统" },
  { modType = 25, name = "车牌架" },
  { modType = 26, name = "个性车牌" },
  { modType = 27, name = "装饰设计" },
  { modType = 28, name = "装饰品" },
  { modType = 29, name = "仪表盘" },
  { modType = 30, name = "表盘设计" },
  { modType = 31, name = "车门扬声器" },
  { modType = 32, name = "座椅" },
  { modType = 33, name = "方向盘" },
  { modType = 34, name = "换挡杆" },
  { modType = 35, name = "铭牌" },
  { modType = 36, name = "音响系统" },
  { modType = 37, name = "后备箱" },
  { modType = 38, name = "液压装置" },
  { modType = 39, name = "引擎缸体" },
  { modType = 40, name = "空气滤清器/增压器" },
  { modType = 41, name = "支柱" },
  { modType = 42, name = "轮拱罩" },
  { modType = 43, name = "天线" },
  { modType = 44, name = "装饰条" },
  { modType = 45, name = "油箱" },
  { modType = 46, name = "左车门" },
  { modType = 47, name = "右车门" },
  { modType = 48, name = "贴纸" },
  { modType = 49, name = "警灯" },

  -- 命名装饰
  { modType = "LIVERY", name = "车身涂装" },
  { modType = "LIVERY_ROOF", name = "车顶涂装" },
  { modType = "PLATE_INDEX", name = "车牌类型", ignorePriceMult = true },
  { modType = "WINDOW_TINT", name = "车窗着色", ignorePriceMult = true }
}

Config.Mods.PlateIndexes = {
  { modIndex = 0, name = "蓝底白字" },
  { modIndex = 1, name = "黄底黑字" },
  { modIndex = 2, name = "黄底蓝字" },
  { modIndex = 3, name = "蓝底白字" },
  { modIndex = 4, name = "蓝底白字" },
  { modIndex = 5, name = "北扬克顿" }, 

  -- mp2023_02 (拆车厂) 仅限
  { modIndex = 6, name = "eCola" },
  { modIndex = 7, name = "拉斯文图斯" },
  { modIndex = 8, name = "自由城" },
  { modIndex = 9, name = "洛圣都车展" },
  { modIndex = 10, name = "洛圣都恐慌" },
  { modIndex = 11, name = "洛圣都磅击者" },
  { modIndex = 12, name = "Sprunk" }
}

Config.Mods.WindowTints = {
  { modIndex = 0, name = "无色调" },
  { modIndex = 3, name = "浅烟色" },
  { modIndex = 2, name = "深烟色" },
  { modIndex = 1, name = "纯黑色" }
}

Config.Mods.WheelTypes = {
  { modIndex = 0, name = "运动型" },
  { modIndex = 1, name = "肌肉型" },
  { modIndex = 2, name = "低骑型" },
  { modIndex = 3, name = "SUV型" },
  { modIndex = 4, name = "越野型" },
  { modIndex = 5, name = "改装型" },
  { modIndex = 6, name = "摩托型" },
  { modIndex = 7, name = "高端型" },
  { modIndex = 8, name = "贝尼原装" },
  { modIndex = 9, name = "贝尼定制" },
  { modIndex = 10, name = "开放式车轮" },
  { modIndex = 11, name = "街道型" },
  { modIndex = 12, name = "赛道型" },
}

Config.Mods.Horns = {
  { modIndex = -1, name = "原装喇叭", musical = false },
  { modIndex = 0,  name = "卡车喇叭", musical = false },
  { modIndex = 1,  name = "警车喇叭", musical = false },
  { modIndex = 2,  name = "小丑喇叭", musical = false },
  { modIndex = 3,  name = "音乐喇叭 1", musical = true },
  { modIndex = 4,  name = "音乐喇叭 2", musical = true },
  { modIndex = 5,  name = "音乐喇叭 3", musical = true },
  { modIndex = 6,  name = "音乐喇叭 4", musical = true },
  { modIndex = 7,  name = "音乐喇叭 5", musical = true },
  { modIndex = 8,  name = "悲伤长号", musical = true },
  { modIndex = 9,  name = "古典喇叭 1", musical = true },
  { modIndex = 10, name = "古典喇叭 2", musical = true },
  { modIndex = 11, name = "古典喇叭 3", musical = true },
  { modIndex = 12, name = "古典喇叭 4", musical = true },
  { modIndex = 13, name = "古典喇叭 5", musical = true },
  { modIndex = 14, name = "古典喇叭 6", musical = true },
  { modIndex = 15, name = "古典喇叭 7", musical = true },
  { modIndex = 16, name = "音阶 - Do", musical = false },
  { modIndex = 17, name = "音阶 - Re", musical = false },
  { modIndex = 18, name = "音阶 - Mi", musical = false },
  { modIndex = 19, name = "音阶 - Fa", musical = false },
  { modIndex = 20, name = "音阶 - Sol", musical = false },
  { modIndex = 21, name = "音阶 - La", musical = false },
  { modIndex = 22, name = "音阶 - Ti", musical = false },
  { modIndex = 23, name = "音阶 - Do", musical = false },
  { modIndex = 24, name = "爵士喇叭 1", musical = true },
  { modIndex = 25, name = "爵士喇叭 2", musical = true },
  { modIndex = 26, name = "爵士喇叭 3", musical = true },
  { modIndex = 27, name = "爵士喇叭循环", musical = true },
  { modIndex = 28, name = "星条旗永不落 1", musical = true },
  { modIndex = 29, name = "星条旗永不落 2", musical = true },
  { modIndex = 30, name = "星条旗永不落 3", musical = true },
  { modIndex = 31, name = "星条旗永不落 4", musical = true },
  { modIndex = 32, name = "古典喇叭 8 循环", musical = true },
  { modIndex = 33, name = "古典喇叭 9 循环", musical = true },
  { modIndex = 34, name = "古典喇叭 10 循环", musical = true },
  { modIndex = 35, name = "古典喇叭 8", musical = true },
  { modIndex = 36, name = "古典喇叭 9", musical = true },
  { modIndex = 37, name = "古典喇叭 10", musical = true },
  { modIndex = 38, name = "葬礼进行曲循环", musical = true },
  { modIndex = 39, name = "葬礼进行曲", musical = true },
  { modIndex = 40, name = "恐怖氛围循环", musical = true },
  { modIndex = 41, name = "恐怖氛围", musical = true },
  { modIndex = 42, name = "圣安地列斯循环", musical = true },
  { modIndex = 43, name = "圣安地列斯", musical = true },
  { modIndex = 44, name = "自由城循环", musical = true },
  { modIndex = 45, name = "自由城", musical = true },
  { modIndex = 46, name = "节日 1 循环", musical = true },
  { modIndex = 47, name = "节日 1", musical = true },
  { modIndex = 48, name = "节日 2 循环", musical = true },
  { modIndex = 49, name = "节日 2", musical = true },
  { modIndex = 50, name = "节日 3 循环", musical = true },
  { modIndex = 51, name = "节日 3", musical = true },
  { modIndex = 52, name = "低音气喇叭循环", musical = false },
  { modIndex = 53, name = "低音气喇叭", musical = false },
  { modIndex = 54, name = "中音气喇叭循环", musical = false },
  { modIndex = 55, name = "中音气喇叭", musical = false },
  { modIndex = 56, name = "高音气喇叭循环", musical = false },
  { modIndex = 57, name = "高音气喇叭", musical = false },
}

Config.Mods.Colours = {
  { name = "主色", paintTypeKey = "paintType1", colourKey = "color1" },
  { name = "副色", paintTypeKey = "paintType2", colourKey = "color2" },
  { name = "珠光色", colourIdKey = "pearlescentColor" },
  { name = "仪表盘", colourIdKey = "dashboardColor" },
  { name = "内饰", colourIdKey = "interiorColor" },
  { name = "轮毂", colourIdKey = "wheelColor" },
}

-- 你可以重命名但不能重新排序这些
Config.Mods.RgbPaintFinishes = {
  "普通",
  "金属漆",
  "珠光漆",
  "哑光",
  "金属",
  "铬"
}

Config.Mods.GtaColours = {
  Metallic = {
    { modIndex = 0, name = "黑色",                    hex = "0d1116" },
    { modIndex = 1, name = "石墨黑",                  hex = "1c1d21" },
    { modIndex = 2, name = "黑钢",                    hex = "32383d" },
    { modIndex = 3, name = "深银",                    hex = "454b4f" },
    { modIndex = 4, name = "银色",                    hex = "999da0" },
    { modIndex = 5, name = "蓝银",                    hex = "c2c4c6" },
    { modIndex = 6, name = "钢灰",                    hex = "979a97" },
    { modIndex = 7, name = "暗影银",                  hex = "637380" },
    { modIndex = 8, name = "石银",                    hex = "63625c" },
    { modIndex = 9, name = "午夜银",                  hex = "3c3f47" },
    { modIndex = 10, name = "枪金属",                 hex = "444e54" },
    { modIndex = 11, name = "煤灰",                   hex = "1d2129" },
    { modIndex = 27, name = "红色",                   hex = "c00e1a" },
    { modIndex = 28, name = "都灵红",                 hex = "da1918" },
    { modIndex = 29, name = "方程式红",               hex = "b6111b" },
    { modIndex = 30, name = "火焰红",                 hex = "a51e23" },
    { modIndex = 31, name = "优雅红",                 hex = "7b1a22" },
    { modIndex = 32, name = "石榴红",                 hex = "8e1b1f" },
    { modIndex = 33, name = "沙漠红",                 hex = "6f1818" },
    { modIndex = 34, name = "赤霞红",                 hex = "49111d" },
    { modIndex = 35, name = "糖果红",                 hex = "b60f25" },
    { modIndex = 36, name = "日出橙",                 hex = "d44a17" },
    { modIndex = 37, name = "经典金",                 hex = "c2944f" },
    { modIndex = 38, name = "橙色",                   hex = "f78616" },
    { modIndex = 49, name = "深绿",                   hex = "132428" },
    { modIndex = 50, name = "赛车绿",                 hex = "122e2b" },
    { modIndex = 51, name = "海绿",                   hex = "12383c" },
    { modIndex = 52, name = "橄榄绿",                 hex = "31423f" },
    { modIndex = 53, name = "绿色",                   hex = "155c2d" },
    { modIndex = 54, name = "汽油蓝绿",               hex = "1b6770" },
    { modIndex = 61, name = "午夜蓝",                 hex = "222e46" },
    { modIndex = 62, name = "深蓝",                   hex = "233155" },
    { modIndex = 63, name = "萨克森蓝",               hex = "304c7e" },
    { modIndex = 64, name = "蓝色",                   hex = "47578f" },
    { modIndex = 65, name = "航海蓝",                 hex = "637ba7" },
    { modIndex = 66, name = "港口蓝",                 hex = "394762" },
    { modIndex = 67, name = "钻石蓝",                 hex = "d6e7f1" },
    { modIndex = 68, name = "冲浪蓝",                 hex = "76afbe" },
    { modIndex = 69, name = "航海蓝",                 hex = "345e72" },
    { modIndex = 70, name = "亮蓝",                   hex = "0b9cf1" },
    { modIndex = 71, name = "紫蓝",                   hex = "2f2d52" },
    { modIndex = 72, name = "帆船蓝",                 hex = "282c4d" },
    { modIndex = 73, name = "极致蓝",                 hex = "2354a1" },
    { modIndex = 74, name = "明亮蓝",                 hex = "6ea3c6" },
    { modIndex = 88, name = "出租车黄",               hex = "ffcf20" },
    { modIndex = 89, name = "赛车黄",                 hex = "fbe212" },
    { modIndex = 90, name = "青铜",                   hex = "916532" },
    { modIndex = 91, name = "黄鸟",                   hex = "e0e13d" },
    { modIndex = 92, name = "青柠",                   hex = "98d223" },
    { modIndex = 93, name = "香槟",                   hex = "9b8c78" },
    { modIndex = 94, name = "普韦布洛米色",           hex = "503218" },
    { modIndex = 95, name = "深象牙",                 hex = "473f2b" },
    { modIndex = 96, name = "巧克力棕",               hex = "221b19" },
    { modIndex = 97, name = "金色棕",                 hex = "653f23" },
    { modIndex = 98, name = "浅棕",                   hex = "775c3e" },
    { modIndex = 99, name = "稻草米色",               hex = "ac9975" },
    { modIndex = 100, name = "苔藓棕",                hex = "6c6b4b" },
    { modIndex = 101, name = "比斯顿棕",              hex = "402e2b" },
    { modIndex = 102, name = "山毛榉木",              hex = "a4965f" },
    { modIndex = 103, name = "深山毛榉木",            hex = "46231a" },
    { modIndex = 104, name = "巧克力橙",              hex = "752b19" },
    { modIndex = 105, name = "沙滩沙",                hex = "bfae7b" },
    { modIndex = 106, name = "阳光漂白沙",            hex = "dfd5b2" },
    { modIndex = 107, name = "奶油",                  hex = "f7edd5" },
    { modIndex = 111, name = "白色",                  hex = "fffff6" },
    { modIndex = 112, name = "霜白",                  hex = "eaeaea" },
    { modIndex = 125, name = "保安公司绿",            hex = "83c566" },
    { modIndex = 137, name = "朱红粉",                hex = "df5891" },
    { modIndex = 141, name = "黑蓝",                  hex = "0a0c17" },
    { modIndex = 142, name = "黑紫",                  hex = "0c0d18" },
    { modIndex = 143, name = "黑红",                  hex = "0e0d14" },
    { modIndex = 145, name = "紫色",                  hex = "621276" },
    { modIndex = 146, name = "极深蓝",                hex = "0b1421" },
    { modIndex = 150, name = "熔岩红",                hex = "bc1917" },
  },
  Matte = {
    { modIndex = 12, name = "黑色",                   hex = "13181f" },
    { modIndex = 13, name = "灰色",                    hex = "26282a" },
    { modIndex = 14, name = "浅灰色",                  hex = "515554" },
    { modIndex = 39, name = "红色",                    hex = "cf1f21" },
    { modIndex = 40, name = "深红色",                  hex = "732021" },
    { modIndex = 41, name = "橙色",                    hex = "f27d20" },
    { modIndex = 42, name = "黄色",                    hex = "ffc91f" },
    { modIndex = 55, name = "酸橙绿",                  hex = "66b81f" },
    { modIndex = 82, name = "深蓝色",                  hex = "1f2852" },
    { modIndex = 83, name = "蓝色",                    hex = "253aa7" },
    { modIndex = 84, name = "午夜蓝",                  hex = "1c3551" },
    { modIndex = 128, name = "绿色",                   hex = "4e6443" },
    { modIndex = 129, name = "棕色",                   hex = "bcac8f" },
    { modIndex = 131, name = "白色",                   hex = "fcf9f1" },
    { modIndex = 148, name = "紫色",                   hex = "6b1f7b" },
    { modIndex = 149, name = "深紫色",                 hex = "1e1d22" },
    { modIndex = 151, name = "森林绿",                 hex = "2d362a" },
    { modIndex = 152, name = "橄榄棕",                 hex = "696748" },
    { modIndex = 153, name = "沙漠棕",                 hex = "7a6c55" },
    { modIndex = 154, name = "沙漠黄",                 hex = "c3b492" },
    { modIndex = 155, name = "叶绿",                   hex = "5a6352" },
  },
  Util = {
    { modIndex = 15, name = "黑色",                   hex = "151921" },
    { modIndex = 16, name = "哑光黑",                 hex = "1e2429" },
    { modIndex = 17, name = "深银色",                 hex = "333a3c" },
    { modIndex = 18, name = "银色",                   hex = "8c9095" },
    { modIndex = 19, name = "枪灰",                   hex = "39434d" },
    { modIndex = 20, name = "暗影银",                 hex = "506272" },
    { modIndex = 43, name = "红色",                   hex = "9c1016" },
    { modIndex = 44, name = "亮红色",                 hex = "de0f18" },
    { modIndex = 45, name = "石榴红",                 hex = "8f1e17" },
    { modIndex = 56, name = "深绿色",                 hex = "22383e" },
    { modIndex = 57, name = "绿色",                   hex = "1d5a3f" },
    { modIndex = 75, name = "深蓝色",                 hex = "112552" },
    { modIndex = 76, name = "午夜蓝",                 hex = "1b203e" },
    { modIndex = 77, name = "蓝色",                   hex = "275190" },
    { modIndex = 78, name = "海沫蓝",                 hex = "608592" },
    { modIndex = 79, name = "闪电蓝",                 hex = "2446a8" },
    { modIndex = 80, name = "毛伊岛蓝",               hex = "4271e1" },
    { modIndex = 81, name = "亮蓝色",                 hex = "3b39e0" },
    { modIndex = 108, name = "棕色",                  hex = "3a2a1b" },
    { modIndex = 109, name = "中棕色",                hex = "785f33" },
    { modIndex = 110, name = "浅棕色",                hex = "b5a079" },
    { modIndex = 122, name = "米白色",                hex = "dfddd0" },
  },    
  Worn = {      
    { modIndex = 21, name = "黑色",                   hex = "1e232f" },
    { modIndex = 22, name = "石墨色",                hex = "363a3f" },
    { modIndex = 23, name = "银灰色",             hex = "a0a199" },
    { modIndex = 24, name = "银色",                  hex = "d3d3d3" },
    { modIndex = 25, name = "蓝银色",             hex = "b7bfca" },
    { modIndex = 26, name = "暗影银色",           hex = "778794" },
    { modIndex = 46, name = "红色",                     hex = "a94744" },
    { modIndex = 47, name = "金色红",              hex = "b16c51" },
    { modIndex = 48, name = "深红色",                hex = "371c25" },
    { modIndex = 58, name = "深绿色",              hex = "2d423f" },
    { modIndex = 59, name = "绿色",                   hex = "45594b" },
    { modIndex = 60, name = "海沫色",                hex = "65867f" },
    { modIndex = 85, name = "深蓝色",               hex = "4c5f81" },
    { modIndex = 86, name = "蓝色",                    hex = "58688e" },
    { modIndex = 87, name = "浅蓝色",              hex = "74b5d8" },
    { modIndex = 113, name = "蜂蜜米色",            hex = "b0ab94" },
    { modIndex = 114, name = "棕色",                  hex = "453831" },
    { modIndex = 115, name = "深棕色",             hex = "2a282b" },
    { modIndex = 116, name = "稻草米色",            hex = "726c57" },
    { modIndex = 121, name = "灰白色",              hex = "eae6de" },
    { modIndex = 123, name = "橙色",                 hex = "f2ad2e" },
    { modIndex = 124, name = "浅橙色",           hex = "f9a458" },
    { modIndex = 126, name = "出租车黄",            hex = "f1cc40" },
    { modIndex = 130, name = "橙色",                 hex = "f8b658" },
    { modIndex = 132, name = "白色",                  hex = "fffffb" },
    { modIndex = 133, name = "橄榄军绿色",       hex = "81844c" },
  },
  Misc = {
    { modIndex = 117, name = "拉丝钢",          hex = "6a747c" },
    { modIndex = 118, name = "拉丝黑钢",    hex = "354158" },
    { modIndex = 119, name = "拉丝铝",      hex = "9ba0a8" },
    { modIndex = 120, name = "铬色",                 hex = "5870a1" },
    { modIndex = 127, name = "警车蓝",        hex = "4cc3da" },
    { modIndex = 134, name = "纯白",             hex = "ffffff" },
    { modIndex = 135, name = "荧光粉",               hex = "f21f99" },
    { modIndex = 136, name = "鲑鱼粉",            hex = "fdd6cd" },
    { modIndex = 138, name = "橙色",                 hex = "f6ae20" },
    { modIndex = 139, name = "绿色",                  hex = "b0ee6e" },
    { modIndex = 140, name = "蓝色",                   hex = "08e9fa" },
    { modIndex = 144, name = "猎人绿",           hex = "9f9e8a" },
    { modIndex = 147, name = "改装店黑",         hex = "11141a" },
    { modIndex = 156, name = "合金色",                  hex = "81827f" },
    { modIndex = 157, name = "伊普西隆蓝",           hex = "afd6e4" },
    { modIndex = 158, name = "纯金",              hex = "7a6440" },
    { modIndex = 159, name = "拉丝金",           hex = "7f6a48" }
  },
  Chameleon = {
    { modIndex = 161, name = "阳极氧化红",             hex = "CF1020" },
    { modIndex = 162, name = "阳极氧化酒红",           hex = "5E1224" },
    { modIndex = 163, name = "阳极氧化紫",             hex = "800080" },
    { modIndex = 164, name = "阳极氧化蓝",             hex = "0000FF" },
    { modIndex = 165, name = "阳极氧化绿",             hex = "008000" },
    { modIndex = 166, name = "阳极氧化青柠",           hex = "AFFF00" },
    { modIndex = 167, name = "阳极氧化铜",             hex = "B87333" },
    { modIndex = 168, name = "阳极氧化青铜",           hex = "CD7F32" },
    { modIndex = 169, name = "阳极氧化香槟",           hex = "F7E7CE" },
    { modIndex = 170, name = "阳极氧化金",             hex = "FFD700" },
    { modIndex = 171, name = "绿色蓝色渐变",           hex = "1164B4" },
    { modIndex = 172, name = "绿色红色渐变",           hex = "B43104" },
    { modIndex = 173, name = "绿色棕色渐变",           hex = "735C12" },
    { modIndex = 174, name = "绿色青色渐变",           hex = "43C6DB" },
    { modIndex = 175, name = "绿色紫色渐变",           hex = "9D00FF" },
    { modIndex = 176, name = "青绿色紫色渐变",         hex = "6A0DAD" },
    { modIndex = 177, name = "青绿色红色渐变",         hex = "E60026" },
    { modIndex = 178, name = "青绿色紫色渐变",         hex = "30D5C8" },
    { modIndex = 179, name = "青色紫色渐变",           hex = "0FF0FC" },
    { modIndex = 180, name = "蓝色粉色渐变",           hex = "4C2882" },
    { modIndex = 181, name = "蓝色绿色渐变",           hex = "138808" },
    { modIndex = 182, name = "紫色红色渐变",           hex = "9B111E" },
    { modIndex = 183, name = "紫色绿色渐变",           hex = "6B2E53" },
    { modIndex = 184, name = "洋红色绿色渐变",         hex = "CA1F7B" },
    { modIndex = 185, name = "洋红色黄色渐变",         hex = "FEDF00" },
    { modIndex = 186, name = "酒红色绿色渐变",         hex = "900020" },
    { modIndex = 187, name = "洋红色青色渐变",         hex = "00FFA1" },
    { modIndex = 188, name = "铜色紫色渐变",           hex = "B87333" },
    { modIndex = 189, name = "洋红色橙色渐变",         hex = "FF5F1F" },
    { modIndex = 190, name = "红色橙色渐变",           hex = "FF4500" },
    { modIndex = 191, name = "橙色紫色渐变",           hex = "B04080" },
    { modIndex = 192, name = "橙色蓝色渐变",           hex = "0047AB" },
    { modIndex = 193, name = "白色紫色渐变",           hex = "F8F0E3" },
    { modIndex = 194, name = "红色彩虹渐变",           hex = "ED2939" },
    { modIndex = 195, name = "蓝色彩虹渐变",           hex = "4B0082" },
    { modIndex = 196, name = "深绿色珍珠",             hex = "013220" },
    { modIndex = 197, name = "深青绿色珍珠",           hex = "008080" },
    { modIndex = 198, name = "深蓝色珍珠",             hex = "000080" },
    { modIndex = 199, name = "深紫色珍珠",             hex = "301934" },
    { modIndex = 200, name = "油彩珍珠",               hex = "4B0082" },
    { modIndex = 201, name = "浅绿色珍珠",             hex = "99E550" },
    { modIndex = 202, name = "浅蓝色珍珠",             hex = "ADD8E6" },
    { modIndex = 203, name = "浅粉色珍珠",             hex = "FFB6C1" },
    { modIndex = 204, name = "米白色珍珠",             hex = "F2F0E6" },
    { modIndex = 205, name = "粉色珍珠",               hex = "EAADEA" },
    { modIndex = 206, name = "黄色珍珠",               hex = "FFF000" },
    { modIndex = 207, name = "绿色珍珠",               hex = "00A550" },
    { modIndex = 208, name = "蓝色珍珠",               hex = "0000FF" },
    { modIndex = 209, name = "奶油珍珠",               hex = "FFFDD0" },
    { modIndex = 210, name = "白色棱镜",               hex = "FFFFFF" },
    { modIndex = 211, name = "石墨棱镜",               hex = "251607" },
    { modIndex = 212, name = "深蓝色棱镜",             hex = "00008B" },
    { modIndex = 213, name = "深紫色棱镜",             hex = "301934" },
    { modIndex = 214, name = "亮粉色棱镜",             hex = "FF69B4" },
    { modIndex = 215, name = "深红色棱镜",             hex = "8B0000" },
    { modIndex = 216, name = "深绿色棱镜",             hex = "013220" },
    { modIndex = 217, name = "黑色棱镜",               hex = "000000" },
    { modIndex = 218, name = "黑色油污",               hex = "121212" },
    { modIndex = 219, name = "黑色彩虹",               hex = "000000" },
    { modIndex = 220, name = "棱镜",                   hex = "CCCCCC" },
    { modIndex = 221, name = "黑色全息",               hex = "101010" },
    { modIndex = 222, name = "白色全息",               hex = "E6E8FA" },
    { modIndex = 223, name = "单色",                   hex = "B4B4B4" },
    { modIndex = 224, name = "昼夜",                   hex = "333366" },
    { modIndex = 225, name = "失败者",                 hex = "550055" },
    { modIndex = 226, name = "极限Sprunk",             hex = "00FF00" },
    { modIndex = 227, name = "罪恶都市",               hex = "FF00FF" },
    { modIndex = 228, name = "合成波之夜",             hex = "FF007F" },
    { modIndex = 229, name = "四季",                   hex = "73C2FB" },
    { modIndex = 230, name = "Maisonette 9 回顾",     hex = "DCDCDC" },
    { modIndex = 231, name = "泡泡糖",                 hex = "FFC0CB" },
    { modIndex = 232, name = "全彩虹",                 hex = "FF0000" },
    { modIndex = 233, name = "日落",                   hex = "FFD700" },
    { modIndex = 234, name = "七宗罪",                 hex = "701C1C" },
    { modIndex = 235, name = "假面骑士",               hex = "1C1C70" },
    { modIndex = 236, name = "色差",                   hex = "D8BFD8" },
    { modIndex = 237, name = "圣诞节",                 hex = "FF0000" },
    { modIndex = 238, name = "温度",                   hex = "FFA07A" },
    { modIndex = 239, name = "黄色橙色珍珠",           hex = "FFAE42" },
    { modIndex = 240, name = "粉色蓝色珍珠",           hex = "D8BFD8" },
    { modIndex = 241, name = "绿色蓝色珍珠",           hex = "3CB371" },
    { modIndex = 242, name = "青绿色黑色珍珠",         hex = "00CED1" }
}
}

Config.Mods.XenonColours = {
  { modIndex = 0,  name = "白色",          hex = "DEDEFF" },
  { modIndex = 1,  name = "蓝色",           hex = "0215FF" },
  { modIndex = 2,  name = "电子蓝",         hex = "0353FF" },
  { modIndex = 3,  name = "薄荷绿",         hex = "00FF8C" },
  { modIndex = 4,  name = "柠檬绿",         hex = "5EFF01" },
  { modIndex = 5,  name = "黄色",           hex = "FFFF00" },
  { modIndex = 6,  name = "金黄淋浴",       hex = "FF9600" },
  { modIndex = 7,  name = "橙色",           hex = "FF3E00" },
  { modIndex = 8,  name = "红色",           hex = "FF0101" },
  { modIndex = 9,  name = "小马粉",         hex = "FF3264" },
  { modIndex = 10, name = "艳粉",           hex = "FF05BE" },
  { modIndex = 11, name = "紫色",           hex = "2301FF" },
  { modIndex = 12, name = "黑光",           hex = "0F03FF" }
}